### ISSUE TITLE
Bug editing time in DatePicker

### ISSUE THREAD

**Issue by jagannathBhat** [bigbinary/neeto-ui#2170] opened 2024-04-19 11:37 UTC
Related to bigbinary/neeto-kb-web#6054

[How to reporduce](https://neeto-engineering.neetoreplay.net/replay/a8aa61c7-7c54-41b4-a63d-8f1485a5a1c1)

**Comment by josephmathew900** [comment] 2024-05-05 03:19
@gaagul _a

**Comment by gaagul** [comment] 2024-05-28 10:16
The issue is being closed as it is no longer reproducible.

**Closed by gaagul** 2024-05-28 10:16 UTC
Labels: bug, 0.5D
