### ISSUE TITLE
Menu Block component throws an error when click on pencil icon

### ISSUE THREAD

**Issue by Harshit-frontend** [bigbinary/neeto-ui#318] opened 2021-06-10 13:00 UTC
<img width="1053" alt="Screenshot 1943-03-20 at 6 24 33 PM" src="https://user-images.githubusercontent.com/83356733/121529344-efbbfd80-ca19-11eb-8a9b-27272162c45d.png">

https://www.loom.com/share/fb1f51da2396447088aa09dfdf0fdc65

**Comment by edwinbbu** [comment] 2021-06-12 15:44
@Harshit-frontend _a, Edit icon in the menubar won't be shown on hover always should fix the issue you mentioned.. (Resolved in PR https://github.com/bigbinary/neeto-ui/pull/307). Please update to the latest version of neetoui and if the issue is valid anymore.

**Closed** 2021-06-14 08:48 UTC
