### ISSUE TITLE
404 page not found toastr shown on each page load

### ISSUE THREAD

**Issue by deepanshu-rajput-git** [bigbinary/neeto-ui#2389] opened 2024-11-28 08:09 UTC
Ref: https://deepanshu-bigbinary.neetorecord.com/watch/70bbabdb-16fa-4793-a95a-ae0d577114aa

@praveen-murali-ind _a, Please take a look at the issue.
bug _t
caught-by-playwright _t
priority _t

**Comment by praveen-murali-ind** [comment] 2024-11-28 08:10
@deepakjosp _a

**Comment by deepakjosp** [comment] 2024-11-28 08:22
@deepanshu-rajput-git the issue is not reproducible in staging or development. Could you please provide the steps to reproduce.

**Comment by deepanshu-rajput-git** [comment] 2024-11-28 10:00
@deepakjosp: I got this error during signup but cannot reproduce it now.

**Comment by deepakjosp** [comment] 2024-11-28 10:07
@deepanshu-rajput-git _a it will probably be an issue within NeetoCal. Could you please assign this to someone from the team?

**Comment by deepanshu-rajput-git** [comment] 2024-11-28 10:09
@sayoojtmc _a, can you please take a look?

**Comment by sayoojtmc** [comment] 2024-11-28 10:35
Tried creating a new org in staging, couldn't reproduce this. Closing for now.

**Closed by sayoojtmc** 2024-11-28 10:35 UTC
Labels: bug, priority, caught-by-playwright
