### ISSUE TITLE
Issue with TimePickerInput styles in "firefox" browser

### ISSUE THREAD

**Issue by gaagul** [bigbinary/neeto-ui#2107] opened 2024-03-05 05:54 UTC
Ref: https://github.com/bigbinary/neeto-kb-web/pull/5854#issuecomment-1976894038

@farhanlatheef _a

**Comment by sandip-mane** [comment] 2024-03-05 05:56
Duplicate of https://github.com/bigbinary/neeto-ui/issues/2108

**Closed by sandip-mane** 2024-03-05 05:56 UTC
