### ISSUE TITLE
Table width is infinitely increasing out of page boundary

### ISSUE THREAD

**Issue by subins2000** [bigbinary/neeto-ui#1169] opened 2022-06-09 10:55 UTC
Found this interesting/weird bug of neetoUI table's width just increasing infinitely. Not sure why it's happening, it only happens on my laptop, others were not able to reproduce it. Perhaps see if you can : https://neeto-cal-web-pr-582.onrender.com/scheduled-meetings/all

I noticed this issue from this PR : https://github.com/bigbinary/neeto-cal-web/pull/582

Heard neetoDesk also faced this issue once.

Video: https://vimeo.com/718660192/539d4bb121

cc @yedhink @sandip-mane @vijay2136

**Comment by yedhink** [comment] 2022-06-09 10:58
@amaldinesh7 _a Can you please take a look into this? We could make a fix for this in neetoCal itself by adding a `max-width` I guess. But please check if this is an issue that can be fixed in neetoUI Table component itself.

cc: @praveen-murali-ind @karthiknmenon

**Comment by amaldinesh7** [comment] 2022-06-10 13:08
@subins2000 _a Since I am not able to reproduce this issue, could you try removing the scrollable wrapper 
![Screenshot 2022-06-10 at 6 37 37 PM](https://user-images.githubusercontent.com/33386004/173071109-f741a04d-5f06-4494-abbd-e43d9e2cf0f7.png)

**Comment by subins2000** [comment] 2022-06-11 08:14
@amaldinesh7 _a Use this dummy PR review for reproducing it https://neeto-cal-web-pr-627.onrender.com/

https://github.com/bigbinary/neeto-cal-web/pull/627

**Comment by amaldinesh7** [comment] 2022-06-11 08:22
> @amaldinesh7 _a Use this dummy PR deploy preview for reproducing it https://neeto-cal-web-pr-627.onrender.com/[scheduled-meetings/all](https://neeto-cal-web-pr-582.onrender.com/scheduled-meetings/all)
> 
> https://github.com/bigbinary/neeto-cal-web/pull/627

I couldn't reproduce it. We'll get on a call.

**Closed as completed** 2022-06-14 08:23 UTC
Labels: bug
