### ISSUE TITLE
Display full text for tabs

### ISSUE THREAD

**Issue by amaljosea** [bigbinary/neeto-ui#266] opened 2021-05-13 01:50 UTC
Please refer https://github.com/bigbinary/aceinvoice-web/issues/7555#issuecomment-834237566

**Comment by edwinbbu** [comment] 2021-05-13 13:21
Seems like duplicate of https://github.com/bigbinary/neeto-ui/issues/233

cc @goutham-subramanyam

**Comment by goutham-subramanyam** [comment] 2021-05-13 13:23
@amaljosea The AceInvoice UI is being updated in the following PR: https://github.com/bigbinary/aceinvoice-web/pull/7620

Closing the issue.

**Closed by goutham-subramanyam** 2021-05-13 13:23 UTC
