### ISSUE TITLE
Fix email overflow issue in sidebar profile section

### ISSUE THREAD

**Issue by amaldinesh7** [bigbinary/neeto-ui#882] opened 2022-02-25 08:59 UTC
Ref - https://github.com/bigbinary/neeto-desk-web/issues/12338

@vysakh-m _a

**Comment by vysakh-m** [comment] 2022-02-25 10:02
@amaldinesh7 The issue seems to be fixed in https://github.com/bigbinary/neeto-ui/pull/879

**Comment by karthiknmenon** [comment] 2022-02-25 10:08
@vysakh-m _a Please confirm and close the issue.

**Comment by vysakh-m** [comment] 2022-02-25 10:28
@karthiknmenon Verified that the issue is fixed in the latest version

**Closed by vysakh-m** 2022-02-25 10:28 UTC
