### ISSUE TITLE
Set the date without requiring ok

### ISSUE THREAD

**Issue by aryanandarnav13** [bigbinary/neeto-ui#1765] opened 2023-08-01 12:14 UTC
Ref: [issue](https://github.com/bigbinary/neeto-planner-web/issues/4329)

**Comment by aryanandarnav13** [comment] 2023-08-01 12:15
@ajmaln _a

**Comment by ajmaln** [comment] 2023-08-01 12:20
While looking into the issue, came across `onSelect` prop which gets executed whenever the user selects a date. This could be used to set the date value as soon as the user clicks on a date or time.

**Comment by ajmaln** [comment] 2023-08-01 12:24
Closing as the issue is resolved.

**Closed by ajmaln** 2023-08-01 12:24 UTC
Labels: 0.25D
