### ISSUE TITLE
[Syncing] form/FormCodeEditor

### ISSUE THREAD

**Issue by yedhink** [bigbinary/neeto-ui#105] opened 2020-12-21 09:35 UTC
https://github.com/bigbinary/neeto-help-web/blob/master/app/javascript/Admin/Components/form/FormCodeEditor.jsx

It's just used at one single spot in the whole codebase. [Refer here](https://github.com/bigbinary/neeto-help-web/blob/37e94f406bb420ed2891c1e275449ab66eca485a/app/javascript/Admin/Components/OrganizationTheme/Template/Edit/index.jsx#L111)

I'm not sure whether this is wrapper component over ace-editor that we currently use in neeto-help. If that is not that case, then we ought to remove this and replace the references with latest component code.

I need your inputs on this.
@edwinbbu _a

cc: @goutham-subramanyam

**Comment by goutham-subramanyam** [comment] 2020-12-21 10:58
We can take this up after [KB Themes Revamp](https://github.com/bigbinary/neeto-help-web/pull/9048) is done.

**Comment by edwinbbu** [comment] 2020-12-22 04:54
@yedhink _a

**Comment by edwinbbu** [comment] 2021-04-23 04:55
@karthiknmenon _a Can you check if the issue is valid anymore.

**Comment by karthiknmenon** [comment] 2021-04-27 07:11
@edwinbbu We are using `FormCodeEditor` only for KB Themes. I don't think we need to sync this to `neetoui`

**Comment by edwinbbu** [comment] 2021-04-30 04:52
Closing the issue as per above comments.

**Closed by edwinbbu** 2021-04-30 04:52 UTC
Labels: on-hold, question
